# This is the configuration file for Rio, an easy to use chat & web framework for
# Python.

[app]
# This is either "website" or "chat"
app-type = "website"
# The name of your Python module
main-module = "app"
# All files which are part of your project. Changes to these will trigger a
# reload and they will be packed up when deploying.
project-files = ["*.py", "/assets/", "/rio.toml"]
